name: Publish release

on:
  release:
    types:
      - published
  # push:
  #   branches:
  #     - 'master'
  #   paths-ignore:
  #     - '**/*.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TWINE_NON_INTERACTIVE: "true"
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      -
        name: Install dependencies
        run: |
          python3 -m venv ./venv && \
          source venv/bin/activate && \
          pip install twine wheel
      -
        name: Build and release
        run: |
          source venv/bin/activate && \
          python setup.py sdist bdist_wheel && \
          twine check dist/* && \
          twine upload dist/*
